version: '3.7'

services:
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: nest
      MONGO_INITDB_ROOT_PASSWORD: nest123
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db

volumes:
  mongo:
